### ISSUE TITLE
Socket hang up when using proxies

### ISSUE THREAD

**Issue by chetanddesai** [requiresafe/cli#2]
I'm getting an `ERROR: socket hang up` when trying to use `requiresafe check` when using an `https_proxy`.  Thanks for supporting proxies, that huge.  Doing a quick search around, it might have to do with handling proxy errors?  A potentially useful [thread](https://github.com/nodejitsu/node-http-proxy/issues/527).

I threw in a stack trace for additional info:
```shell
SDGL1200d1fd4:node-service-example cdesai$ requiresafe check
Trace: { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
    at /usr/lib/node_modules/requiresafe/lib/commands/check.js:36:21
    at Request._callback (/usr/lib/node_modules/requiresafe/node_modules/requiresafe-sdk/rs-sdk.js:168:20)
    at self.callback (/usr/lib/node_modules/requiresafe/node_modules/requiresafe-sdk/node_modules/request/request.js:368:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (/usr/lib/node_modules/requiresafe/node_modules/requiresafe-sdk/node_modules/request/request.js:1025:8)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1551:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1410:15)
    at SecurePair.emit (events.js:95:17)
>> ERROR: socket hang up
```

**Comment by bear** [comment]
Thanks for the testing the CLI and reporting this issue!

**Comment by chetanddesai** [comment]
I was able to get this working by setting `config.tunnel = true;` in the version `1.2.0` of the requiresafe SDK. See https://github.com/requiresafe/sdk/blob/v1.2.0/rs-sdk.js#L162.  It seems like the requiresafe SDK might be moving in a different direction in the latest 3.X releases, not sure how the `http_proxy` mechanism is used in the latest SDK.  Any suggestions for how to move forward with this one? I'm happy to help.

**Comment by bear** [comment]
We will need to ensure that the SDK is proxy aware, so nothing *should* change with that. I need to talk to the api/sdk devs about this issue and get back to you.

**Comment by chetanddesai** [comment]
Awesome, thanks @bear!

**Comment by bear** [comment]
@chetanddesai - FYI - Issue https://github.com/requiresafe/requiresafe/issues/72 should be getting closed soon, the proxy lib that it depended on accepted our PR 

That should clear the way for this issue to be resolved, but I'll let @nlf say that :)

**Comment by chetanddesai** [comment]
Sweet.  Sounds good @bear; appreciate the update!

**Comment by nlf** [comment]
version 1.5.0 of the CLI and version 3.2.0 of the SDK now have support for proxies, let me know if you continue to have issues @chetanddesai
