### ISSUE TITLE
Getting 404s when installing with old npm

### ISSUE THREAD

**Issue by naugtur** [requiresafe/cli#26]
When requiresafe is in devDependencies, I get a 404 on requiresafe.
When installing manually, I get: 
```
$ npm install requiresafe
npm WARN package.json datajs@1.0.3 No repository field.
npm WARN package.json datajs@1.0.3 No README data
npm WARN package.json mustache@0.7.2 No repository field.
npm WARN package.json consolidate@0.9.0 No repository field.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'requiresafe/npm-utils' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'requiresafe'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-65-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "requiresafe"
npm ERR! cwd /home/zb/tmp
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```

Works fine when I switch to node 4.x environment.

**Comment by latentflip** [comment]
You don't need to be all the way on node 4, but you do need to have a version of npm which supports scoped modules (which is greater than 2.7).

Though it's possible we should just publish the single scoped-dependency as an unscoped one for the cli to avoid this issue. @nlf? @evilpacket?

**Comment by pdehaan** [comment]
Yeah, I think this is the same as #22.
Not sure if we should add `engines` to the requiresafe/cli module's package.json to specify that this only works with npm@2: https://docs.npmjs.com/files/package.json#engines

**Comment by naugtur** [comment]
If you want o know my opinion, you should absolutely add that. Putting requirements in package.json is the best option.

For me it stopped working in a CI environment that was running test on oldest supported node version (where having run the tests, it'd audit dependencies with requiresafe)
and at first I had no idea why that happened. Old node was the obvious guess, but knowing which exact version is needed puts me in a much better situation.

**Comment by evilpacket** [comment]
@naugtur thanks. Pretty sure we'll get this in the next release. Sorry for the trouble.

**Comment by naugtur** [comment]
@evilpacket No prob. Requiresafe is saving me trouble of inspecting packages myself. 
Totally worth the effort for an occasional issue report ;)
