### ISSUE TITLE
Export .eslintrc file as new eslint-config-requiresafe module so it can be shared with our requiresafe/* repos?

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/cli#31]
If somebody wants to create a **requiresafe/eslint-config-requiresafe** repo, I can submit the PR to that repo and then update this repo to use the shared config.

Then we can easily share the config between the **gulp-requiresafe** and **grunt-requiresafe** repos (and whatever other repos).

**Comment by nlf** [comment]
created requiresafe/eslint-config-requiresafe and will switch this project to it, good idea :+1:
