### ISSUE TITLE
Add eslint as a devDep?

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/cli#32]
Not 100% following what's happening with the flattened directory structure, but it seems like there is **eslint**, **eslint-config-hapi**, and **eslint-plugin-hapi** in the npm-shrinkwrap.json file, but they aren't in the top level devDeps of this repo. Not sure if this could cause some potential breakage if somebody happens to re-shrinkwrap this repo with npm@2.

```js
    "eslint": {
      "version": "1.5.1",
      "dependencies": {
        "minimatch": {
          "version": "2.0.10"
        },
        "strip-json-comments": {
          "version": "1.0.4"
        }
      }
    },
    "eslint-config-hapi": {
      "version": "3.0.1"
    },
    "eslint-plugin-hapi": {
      "version": "1.2.0"
    },
```

**Comment by pdehaan** [comment]
Also odd is that it doesn't seem like you can run `eslint .` directly from this repo via the CLI (using a globally installed **eslint@1.7.x**).

```
$ npm version
{ requiresafe: '2.1.1',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }

$ eslint .
/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:213
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-hapi'
Referenced from: /Users/pdehaan/dev/tmp/del/requiresafe-cli/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readConfigFromFile (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:155:44)
    at loadConfig (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:176:22)
    at /Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:191:36)
    at getLocalConfig (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:321:23)

$ ./node_modules/.bin/eslint .

$ echo $?
0

$ eslint --version # v1.7.1
```

### Workaround:
Call `eslint` via the local **eslint** version instead of a global version:
```sh
./node_modules/.bin/eslint .
```

OR
Create a shortcut script in the package.json file:
```
"lint": "eslint ."
```

Then you can run `$ npm run lint` and it will properly resolve the locally installed ESLint and plugins/configs.

**Comment by pdehaan** [comment]
This seems to have removed ESLint from the npm-shrinkwrap.json file:

```
$ npm ls --depth 0
requiresafe@2.2.1 /Users/pdehaan/dev/tmp/del/requiresafe-cli
├── ...
├── escape-string-regexp@1.0.3
├── eslint-config-requiresafe@1.0.0
├── extend@3.0.0
├── ...
```

I had to manually install it using:
```
$ npm i eslint eslint-config-hapi -D
```

(If I was using **npm@3**, I think I'd also need to explicitly install the **eslint-plugin-hapi** peer module.)

**Comment by nlf** [comment]
i assume you mean when cloning the repo and running it from there? you're right, i generated the shrinkwrap based on `npm install --production` so any dev dependencies are excluded from the shrinkwrap.

makes local development a bit more of a hassle, but end user experience will be much improved.

we'd have to go through and make sure every subdependency of every dev dependency was added as a top level dev dependency to let them work together more smoothly, so this felt like a good stopgap measure.
